---
title: "igraph-project"
author: "Wojciech Mikołajczyk"
date: "May 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r download dataset}
library(RCurl)

datasetUrl = "http://www.sociopatterns.org/wp-content/uploads/2016/06/tij_InVS.dat_.zip"
datasetMetaUrl = "http://www.sociopatterns.org/wp-content/uploads/2016/06/metadata_InVS13.txt"
datasetFilename = "workplace.zip"
datasetMetaFilename = "workplace_meta.csv"

# dataset file (timestamp node1_id node2_id)
datasetBin = getBinaryURL(datasetUrl)
destFile = file(datasetFilename, open="wb")
writeBin(datasetBin, destFile)
close(destFile)
unzip(datasetFilename)
if (file.exists(datasetFilename))
{
    file.remove(datasetFilename)
}
file.rename("tij_InVS.dat", "workplace_dataset.csv")

# metadata file (node_id node_attribute)
datasetMeta = getURL(datasetMetaUrl)
destMetaFile = file(datasetMetaFilename, open="w")
write(datasetMeta, destMetaFile)
close(destMetaFile)
```

```{r load graph}
library(igraph)

nodes <- read.csv(datasetMetaFilename, sep="\t", header=FALSE)
links <- read.csv("workplace_dataset.csv", sep=" ", header=FALSE, colClasses = c("NULL", NA, NA))

net <- graph_from_edgelist(as.matrix(links))
net <- set_vertex_attr(net, "department", index=nodes$V1, as.character(nodes$V2))
# set initial weight of all edges to 1
E(net)$weight <- 1
# adjust weights
net <- simplify(net, edge.attr.comb=list(weight="sum"))
# make graph undirected (meeting of 2 people is like undirected relation)
net <- as.undirected(net, mode="collapse", edge.attr.comb="sum")
# delete unconnected verticles
net <-delete.vertices(net, degree(net)==0)
```

```{r plot1 - verticle color based on attribute value, edge thickness depends on edge weight}
library(RColorBrewer)
numberOrDepartments <- length(unique(V(net)$department))
myColors <- brewer.pal(numberOrDepartments,"Set1")

plot(
  net,
  # weight based on edge
  edge.width=E(net)$weight/10,
  # colors
  vertex.color = myColors[as.numeric(as.factor(V(net)$department))],
  vertex.size=10
)
```

```{r plot2 - verticle size depends of verticle betweenness, edge thickness depends on edge betweenness}
plot(
  net,
  # edge thickness depending on edge betweenness
  edge.width=edge_betweenness(net, directed=FALSE, weights = E(net)$weight)/50,
  # vertex size based on betweenness
  vertex.size=betweenness(net, directed=FALSE, weights=E(net)$weight)/10
)
```

```{r plot3 - show longest shortest path}
# shortest paths
shortestPaths <- distances(net)
longestShortestPath <- which(shortestPaths==max(shortestPaths), arr.ind = TRUE)[1,]
node1 <- longestShortestPath[1]
node2 <- longestShortestPath[2]

net.path = shortest_paths(net, from=node1, to=node2, output="both")
# edges colors
ecol <- rep("gray80", ecount(net))
ecol[unlist(net.path$epath)] <- "orange"
# edges width
ew <- rep(0.5, ecount(net))
ew[unlist(net.path$epath)] <- 5
# verticles color
vcol <- rep("gray40", vcount(net))
vcol[unlist(net.path$vpath)] <- "gold"
# verticles size
vsize <-rep(7, vcount(net))
vsize[unlist(net.path$vpath)] <- 14

plot(
  net,
  # edges - color and width
  edge.color=ecol,
  edge.width=ew,
  # verticles - color and size
  vertex.color=vcol,
  vertex.size=vsize
)
```

```{r plot4 - largest clique}
largest_clique <- largest_cliques(net)[1]
# color
vcol <- rep("grey80", vcount(net))
vcol[unlist(largest_clique)] <- "gold"
# size
vsize <- rep(7, vcount(net))
vsize[unlist(largest_clique)] <- 10

clique_edges = get.edge.ids(net, unlist(largest_clique))
ecol <- rep("gray80", ecount(net))
ecol[clique_edges] <- "gold"

ew <- rep(0.5, ecount(net))
ew[clique_edges] <- 5

plot(
  net,
  vertex.color=vcol,
  vertex.size=vsize,
  edge.color=ecol,
  edge.width=ew
)
```

```{r plot5 - vertex degree distribution}
distribution <- degree_distribution(net, cumulative=TRUE)
plot(distribution)
# TODO: ggplot
```

```{r plot6 - distance from one vertex to the others}
dist <- distances(net, v=1, to=V(net))
plot(as.numeric(dist))
```
